export const courseDetailBreadCrumb = [
	{
		href: '/',
		title: 'Home',
	},
	{
		href: '/programming',
		title: 'Programming',
	},
];

export const courseDetailData = [
	{
		courseCategory: 'FREE',
		courseID: 'HL-HTML-101',
		tag: 'HTML',
		courseDetail: {
			title: 'HTML For Absolute Beginners',
			imgURL: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/1200px-HTML5_logo_and_wordmark.svg.png',
			description: 'Collaborated with Daffodil International University',
			price: 0,
			rating_n_review: {
				rating: 4.5,
				totalReview: 275,
				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
	{
		courseCategory: 'FREE',
		courseID: '102',
		tag: 'CSS',
		courseDetail: {
			title: 'CSS For Absolute Beginners',
			imgURL: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/1200px-CSS3_logo_and_wordmark.svg.png',
			description: 'Collaborated with Daffodil International University',
			price: 0,
			rating_n_review: {
				rating: 3,
				totalReview: 275,
				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
	{
		courseCategory: 'PAID',
		courseID: '103',
		tag: 'JS(JavaScript)',
		courseDetail: {
			title: 'Basic JavaScript For Absolute Beginners',
			imgURL: 'https://www.pngitem.com/pimgs/m/116-1167737_logo-javascript-pattern-copyright-framework-free-download-javascript.png',
			description: 'Collaborated with Daffodil International University',
			price: 1200,
			rating: 4.1,
			rating_n_review: {
				totalReview: 275,

				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
	{
		courseCategory: 'FREE',
		courseID: '104',
		tag: 'C Programming',
		courseDetail: {
			title: 'Basic C Programming For Beginners',
			imgURL: 'https://content.techgig.com/thumb/msid-75551562,width-860,resizemode-4/C-programming-language-rises-amid-COVID-19.jpg?72434',
			description: 'Collaborated with Daffodil International University',
			price: 0,
			rating_n_review: {
				rating: 5,
				totalReview: 275,
				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
	{
		courseCategory: 'FREE',
		courseID: '105',
		tag: 'Basic C++ Programming',
		courseDetail: {
			title: 'C++ Programming For Absolute Beginners',
			imgURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKBx4Anw-MIzzIRoWA20hmydbMuc7LxvGTscjQKYLBuDcUC5QurkIuZX2XOFZjGpETQAQ&usqp=CAU',
			description: 'Collaborated with Daffodil International University',
			price: 0,
			rating_n_review: {
				rating: 4.2,
				totalReview: 275,
				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
	{
		courseCategory: 'FREE',
		courseID: '106',
		tag: 'Basic Python Learning',
		courseDetail: {
			title: 'Basic Python For Absolute Beginners',
			imgURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr3sDUaFY20j56B8yPYPGjQmHpshAEaMNezQ&usqp=CAU',
			description: 'Collaborated with Daffodil International University',
			price: 0,
			rating_n_review: {
				rating: 4.4,
				totalReview: 275,
				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
	{
		courseCategory: 'FREE',
		courseID: '107',
		tag: 'Basic Computer Learning',
		courseDetail: {
			title: 'Computer Learning For Beginners',
			imgURL: 'https://content.techgig.com/thumb/msid-75551562,width-860,resizemode-4/C-programming-language-rises-amid-COVID-19.jpg?72434',
			description: 'Collaborated with Daffodil International University',
			price: 0,
			rating_n_review: {
				rating: 4.4,
				totalReview: 275,
				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
	{
		courseCategory: 'FREE',
		courseID: '108',
		tag: 'Physics Quantum Theory Learning',
		courseDetail: {
			title: 'Physics Quantum Theory Learning',
			imgURL: 'https://online.stanford.edu/sites/default/files/styles/figure_default/public/2018-09/quantum-mechanics-for-scientists-engineers_SOE-YEEQMSE01.jpg?itok=KKZKLf5_',
			description: 'Collaborated with Daffodil International University',
			price: 0,
			rating_n_review: {
				rating: 4.4,
				totalReview: 275,
				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
	{
		courseCategory: 'PAID',
		courseID: '109',
		tag: 'ICT Learning',
		courseDetail: {
			title: 'ICT Learning For Absolute Beginners',
			imgURL: 'https://storage.googleapis.com/bucket-newzbusiness-com/2020/12/89ca2042-huawei-partnered-with-the-unesco-institute-for-information-technologies-in-education-iite-750x430.jpg',
			description: 'Collaborated with Daffodil International University',
			price: 1000,
			rating: 4.4,
			rating_n_review: {
				totalReview: 275,

				ratings: [
					{ ratingOf: 5, total: 23 },
					{ ratingOf: 4, total: 14 },
					{ ratingOf: 3, total: 17 },
					{ ratingOf: 2, total: 8 },
					{ ratingOf: 1, total: 5 },
				],
			},
			instructors: ['Mahi', 'Nur'],
			numberOfStudents: 325,
			lastUpdated: '01-01-2022',
			language: ['English', 'Bangla'],
			includes: ['60 hours video.', '20 Articles.', '30 Downloadable resources.', 'Lifetime access.'],
		},
	},
];

export const studentsReviewsData = [
	{
		stduentName: 'Rony',
		title: 'Awesome Course!',
		detail: 'Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Vestibulum id ligula porta felis euismod semper.',
		place: 'New Delhi',
		date: 'Today',
		rating: 5,
	},

	{
		stduentName: 'Hasan',
		title: 'Excelent I never did this type of courses',
		detail: 'Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Vestibulum id ligula porta felis euismod semper.',
		place: 'New Delhi',
		date: '3 days ago',
		rating: 4,
	},
	{
		stduentName: 'Mahee',
		title: 'Not so good, I already know all of them',
		detail: 'Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Vestibulum id ligula porta felis euismod semper.',
		place: 'New Delhi',
		date: '2nd Jan 2021',
		rating: 1,
	},
	{
		stduentName: 'Nur',
		title: 'Very Informative',
		detail: 'Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Vestibulum id ligula porta felis euismod semper.',
		place: 'New Delhi',
		date: '1st Jan 2021',
		rating: 2,
	},
];

export const faqData = [
	{
		question: 'How to Enroll?',
		ans: 'If you subscribed, you get a 7-day free trial during which you can cancel at no penalty. After that, we don’t give refunds, but you can cancel your subscription at any time.',
	},
	{
		question: 'What is the refund policy?',
		ans: 'Yes! To get started, click the course card that interests you and enroll. You can enroll and complete the course to earn a shareable certificate, or you can audit it to view the course materials for free. When you subscribe to a course that is part of a Certificate, you’re automatically subscribed to the full Certificate. Visit your learner dashboard to track your progress.',
	},
	{
		question: 'Is this course really 100% online? Do I need to atten any classes in person?',
		ans: 'This course is completely online, so there’s no need to show up to a classroom in person. You can access your lectures, readings and assignments anytime and anywhere via the web or your mobile device.',
	},
	{
		question: 'How long does it take to complete the Professinal Certificate?',
		ans: 'Approximately 5 months at 5 hours a week.',
	},
	{
		question: 'What background knowledge is necessary?',
		ans: 'No background knowledge is necessary. This Specialization is designed for those new to social media marketing, but no matter where you are in your social media marketing journey, you’ll gain value from deepening your knowledge through this Specialization.',
	},
	{
		question: 'Do I need to take the courses in a specific order?',
		ans: 'Should you decide to take all or some of the courses, we highly encourage you to take them in the suggested order, as we have designed the courses to work in sequence.Course 1 - Introduction to Social Media Marketing. Course 2 - Social Media Management. Course 3 - Fundamentals of Social Media Advertising. Course 4 - Advertising With Meta Ads Manager. Course 5 - Measure and Optimize Social Media Marketing Campaigns. Course 6 - Facebook Social Media Marketing Capstone',
	},
	{
		question: 'Will I earn university credit for completing the Specialization?',
		ans: 'Did you know you can earn up to 2 college credits at participating colleges and universities nationwide for completing a Meta Social Media Marketing Professional Certificate? The Meta Social Media Marketing Professional Certificate is now ACE® recommended. Whether you’re looking for a job or continuing to higher education, this online training program can help you take the next step in your journey. We’ll share on how you can share proof of completion to your school once you complete the certificate program. Please note that the decision to accept specific credit recommendations is up to each institution and is not guaranteed. Read more about ​ACE Credit College & University Partnerships here.  ',
	},
	{
		question: 'What will I be able to do upon completing the Specialization?',
		ans: 'You will know how to create a social media presence for a business. You’ll know how to create engaging content, interact with users on social media, manage a content calendar, and evaluate the success of your posts. You’ll also know how to create effective ads for social media and learn how to create ads in Meta Ads Manager. You’ll know how to match the ads you create to your marketing objectives, select the right images and copy for your ads, get your message in front of your target audience, and measure the impact of your campaign. You’ll also learn how to communicate your campaign results to other people in the company. ',
	},
	{
		question: 'Will I only learn about Facebook and Instragram?',
		ans: 'No. You’ll gain a basic understanding of how the main social media platforms — like Twitter, Pinterest, LinkedIn, TikTok, and more — function and how businesses can use them for their marketing needs. You will learn how to develop effective ads for different social media platforms, but this program specifically focuses on how to develop these ads using Meta’s Ads Manager (for advertising on both Facebook and Instagram). While ad creation tools for different social media platforms differ, understanding how Meta Ads Manager works will help you quickly find your way around other advertising tools (though this program does not focus on how to use other advertising tools). ',
	},
];
