export const homePageData = [
	{
		articleType: 'article',
		publishDate: '22-12-2020',
		postTime: '6:30 PM',
		likesCount: 132,
		comments: ['nice', 'good'],
		postBy: 'Jahidun Nur Mahee',
		postByDetails: {
			fullName: 'Jahidun Nur Mahee',
			firstName: 'Jahidun Nur',
			lastName: 'Mahee',
			profileUrl: '',
			avatarUrl: '',
		},
		title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
		shortDescription:
			'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		articleDetails: {
			title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
			banner: '',
			images: ['', ''],
			video: '',
			moreVideos: ['', ''],
			description:
				'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		},
	},
	{
		articleType: 'article',
		publishDate: '22-12-2020',
		postTime: '6:30 PM',
		likesCount: 132,
		comments: ['nice', 'good'],
		postBy: 'Mahee Nur',
		postByDetails: {
			fullName: 'Mahee Nur',
			firstName: 'Jahidun Nur',
			lastName: 'Mahee',
			profileUrl: '',
			avatarUrl: '',
		},
		title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
		shortDescription:
			'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		articleDetails: {
			title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
			banner: '',
			images: [''],
			video: '',
			moreVideos: [''],
			description:
				'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		},
	},
	{
		articleType: 'video',
		publishDate: '22-12-2020',
		postTime: '6:30 PM',
		likesCount: 132,
		comments: ['nice', 'good'],
		postBy: 'Jahidun Mahee',
		postByDetails: {
			fullName: 'Jahidun Mahee',
			firstName: 'Jahidun Nur',
			lastName: 'Mahee',
			profileUrl: '',
			avatarUrl: '',
		},
		title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
		shortDescription:
			'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		videoURL: 'https://www.youtube.com/watch?v=tlThdr3O5Qo',
		articleDetails: {
			title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
			banner: '',
			images: [''],
			video: '',
			moreVideos: [''],
			description:
				'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		},
	},
	{
		articleType: 'article',
		publishDate: '22-12-2020',
		likesCount: 132,
		postTime: '6:30 PM',
		comments: ['nice', 'good'],
		postBy: 'Nur Mahee',
		postByDetails: {
			fullName: 'Nur Mahee',
			firstName: 'Jahidun Nur',
			lastName: 'Mahee',
			profileUrl: '',
			avatarUrl: '',
		},
		title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
		shortDescription:
			'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		articleDetails: {
			title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
			banner: '',
			images: [''],
			video: '',
			moreVideos: [''],
			description:
				'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		},
	},
	{
		articleType: 'article',
		publishDate: '22-12-2020',
		postTime: '6:30 PM',
		likesCount: 132,
		comments: ['nice', 'good'],
		postBy: 'Jahidun Nur Mahee 2',
		postByDetails: {
			fullName: 'Jahidun Nur Mahee 2',
			firstName: 'Jahidun Nur',
			lastName: 'Mahee',
			profileUrl: '',
			avatarUrl: '',
		},
		title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
		shortDescription:
			'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		articleDetails: {
			title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
			banner: '',
			images: [''],
			video: '',
			moreVideos: [''],
			description:
				'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		},
	},
	{
		articleType: 'article',
		publishDate: '22-12-2020',
		postTime: '6:30 PM',
		likesCount: 132,
		comments: ['nice', 'good'],
		postBy: 'Jahidun Nur Mahee 3',
		postByDetails: {
			fullName: 'Jahidun Nur Mahee 3',
			firstName: 'Jahidun Nur',
			lastName: 'Mahee',
			profileUrl: '',
			avatarUrl: '',
		},
		title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
		shortDescription:
			'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		articleDetails: {
			title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
			banner: '',
			images: [''],
			video: '',
			moreVideos: [''],
			description:
				'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		},
	},
	{
		articleType: 'article',
		publishDate: '22-12-2020',
		postTime: '6:30 PM',
		likesCount: 132,
		comments: ['nice', 'good'],
		postBy: 'Jahidun Nur Mahee 4',
		postByDetails: {
			fullName: 'Jahidun Nur Mahee 4',
			firstName: 'Jahidun Nur',
			lastName: 'Mahee',
			profileUrl: '',
			avatarUrl: '',
		},
		title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
		shortDescription:
			'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		articleDetails: {
			title: 'Tesla’s mission is to accelerate the world’s transition to sustainable energy.',
			banner: '',
			images: [''],
			video: '',
			moreVideos: [''],
			description:
				'Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.',
		},
	},
];
